name: Test-Build-Local
  main-server:
    build: ./
    container_name: main-server
    image: artofimagination/main-server
    ports:
      - 3000:3000
on:
  push:
    branches:
      - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      # INstall Node on the runner
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      # Install all dependencies
      - name: install all dependencies
        run: npm i 
      # Install the newman command line utility and also install the html extra reporter
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
       # Make directory to upload the test results
      - name: Make Directory for results
        run: mkdir -p testResults
      - name: Start test server
        run: docker-compose up -d main-server
      # Run the POSTMAN collection
      - name: Run POSTMAN collection
        run: |
          newman run "store.postman_collection.json" -r htmlextra --reporter-htmlextra-export testResults/index1.html 

      # Upload the contents of Test Results directory to workspace
      - name: Output the run Details
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: RunReports
          path: ./testResults
      - name: Deploy to pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: ./testResults

